### ISSUE TITLE
Help with Rewards on deathrun server

### ISSUE THREAD

**Issue by paldog** [ceifa/lory-gmod-servers#85]
How can i add my own steam group on the rewards config? and the steamtag reward? i need help with that… Thanks by the way. Im using pointshop 2, i dont use the lory pointshop, i need to change some configurations…?

**Comment by ceifa** [comment]
Steam group is configured in this line(you can get your group id on the group url):
https://github.com/ceifa/lory-gmod-servers/blob/b630a9803289624cc6edf46ab291813ef1ee1e89/servers/_shared/rewards/lua/rewards/prizes/steam.lua#L4

The steam tag logic is done on pointshop, in this line:
https://github.com/ceifa/lory-gmod-servers/blob/eee8de96cf4591bf35911f6b1b03e7373765ac96/servers/_shared/pointshop/lua/pointshop/sv_player_extension.lua#L131

At this point is a little bit harder to provide support for pointshop 2, I don't recommend you to use this reward addon.

**Comment by paldog** [comment]
> Steam group is configured in this line(you can get your group id on the group url):
> 
>   
>     
>       lory-gmod-servers/servers/_shared/rewards/lua/rewards/prizes/steam.lua
>     
>     
>          Line 4
>       in
>       b630a98
>     
>     
>     
>     
> 
>         
>           
>            PRIZE.GroupId = "lorybr" 
>         
>     
>   
> 
> 
> The steam tag logic is done on pointshop, in this line:
> 
>   
>     
>       lory-gmod-servers/servers/_shared/pointshop/lua/pointshop/sv_player_extension.lua
>     
>     
>          Line 131
>       in
>       eee8de9
>     
>     
>     
>     
> 
>         
>           
>            return string.match(string.lower(self:GetName()), "lory") or self:PS_HasItemEquipped("doublepoints") 
>         
>     
>   
> 
> 
> At this point is a little bit harder to provide support for pointshop 2, I don't recommend you to use this reward addon.

thank u very muchh

**Comment by paldog** [comment]
ok i delete the steamtag reward, but in the steamgroup reward, in the pointshop points and that stuff, i need to change the ''ps'' of pointshop to''ps2''? because in the console drops me 

[ERROR] addons/rewards/lua/rewards/prizes/steam.lua:2: attempt to index global 'PS' (a nil value)
  1. unknown - addons/rewards/lua/rewards/prizes/steam.lua:2
   2. include - [C]:-1
    3. LoadRewards - addons/rewards/lua/rewards/sv_rewards.lua:9
     4. unknown - addons/rewards/lua/autorun/rewards_init.lua:15


[ERROR] addons/rewards/lua/rewards/sv_rewards.lua:10: attempt to concatenate field 'Image' (a nil value)
  1. LoadRewards - addons/rewards/lua/rewards/sv_rewards.lua:10
   2. unknown - addons/rewards/lua/autorun/rewards_init.lua:15
